/**:
  ros__parameters:
    x_lim: [-17,17]
    y_lim: [-10,10]
    # vx_lim: [-1.2,1.2]
    # vy_lim: [-1.2,1.2]
    #model_dt: 0.01 #update the model with this time step
    sim_dt: 0.01  # update the rvo algo with this rate

    # Robot physical parameters (shared across all nodes) (amr 200)
    cbf:
      lf: 1.2
      lr: 1.2
      wheel_base: 2.4
      robot_width: 2.4
      robot_length: 2.4
      lane_width: 3.4


    # Motion limits (shared across all nodes)
    FollowPath:
      vx_max: 1.5 
      vx_min: -0.5
      vy_max: 0.0
      wz_max: 1.0
      wz_min: -1.0
      ax_max: 0.6 
      ax_min: -0.6 
      az_max: 1.5 


    agents:
      num_agents: 2
      vx_max: 1.5 
      vx_min: -0.5 
      vy_max: 0.0
      wz_max: 1.0
      wz_min: -1.0
      ax_max: 0.6 
      ax_min: -0.6 
      az_max: 1.5 
      lf: 1.2
      lr: 1.2
      wheel_base: 2.4
      robot_width: 2.4
      robot_length: 2.4

      agent_1:
        position: [-14.0, +1.7, 0.0, 0.0]  # [x, y, z, yaw]
        type: "differential"
        shape: "recatangle"
        footprint:
          footprint_shape: "rectangle"
          footprint_radius: 0.8
          footprint_color: [1.0, 0.0, 0.0, 1.0]
          footprint_vis_width: 0.8
        color: [0.0, 0.0, 1.0, 1.0]
        pref_velocity: [0.2, 0.0]
        goal: [6.0, 0.0, 0.0, 0.0]
        publish_debug_msg: true
        # vehicle dynamics params (differential drive)
        num_states: 5
        num_control_inputs: 2
        init_vx: 0.0
        init_wz: 0.0
        init_acc: 0.0
        init_alpha: 0.0
        collision_foot_print_major_axis: 0.8
        collision_foot_print_minor_axis: 0.4
        pos_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 173
        vel_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 273

      agent_2:
        position: [+5.0, -1.7 , 0.0, 3.14]  # [x, y, z, yaw]
        type: "differential"
        shape: "recatangle"
        footprint:
          footprint_shape: "rectangle"
          footprint_radius: 0.8
          footprint_color: [1.0, 0.0, 0.0, 1.0]
          footprint_vis_width: 0.8
        color: [1.0, 0.55, 0.0, 1.0]
        pref_velocity: [-0.2, 0.0]
        goal: [0.0, 0.0, 0.0, 0.0]
        publish_debug_msg: false
        # vehicle dynamics params (differential drive)
        num_states: 5
        num_control_inputs: 2
        init_vx: 0.0
        init_wz: 0.0
        init_acc: 0.0
        init_alpha: 0.0
        collision_foot_print_major_axis: 0.8
        collision_foot_print_minor_axis: 0.4
        pos_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 373
        vel_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 1473  

      agent_3:
        position: [+0.0, -0.8, 0.0, 3.14]  # [x, y, z, yaw]
        type: "differential"
        shape: "recatangle"
        footprint:
          footprint_shape: "rectangle"
          footprint_radius: 0.8
          footprint_color: [1.0, 0.0, 0.0, 1.0]
          footprint_vis_width: 0.8
        color: [0.0, 1.0, 0.0, 1.0]
        pref_velocity: [-0.2, 0.0]
        goal: [0.0, 0.0, 0.0, 0.0]
        publish_debug_msg: false
        # vehicle dynamics params (differential drive)
        num_states: 5
        num_control_inputs: 2
        init_vx: 0.0
        init_wz: 0.0
        init_acc: 0.0
        init_alpha: 0.0
        collision_foot_print_major_axis: 0.8
        collision_foot_print_minor_axis: 0.4
        pos_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 373
        vel_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 1473

      agent_4:
        position: [+3.0, -0.8, 0.0, 3.14]  # [x, y, z, yaw]
        type: "differential"
        shape: "recatangle"
        footprint:
          footprint_shape: "rectangle"
          footprint_radius: 0.8
          footprint_color: [1.0, 0.0, 0.0, 1.0]
          footprint_vis_width: 0.8
        color: [1.0, 0.0, 1.0, 1.0]
        pref_velocity: [-0.2, 0.0]
        goal: [0.0, 0.0, 0.0, 0.0]
        publish_debug_msg: false
        # vehicle dynamics params (differential drive)
        num_states: 5
        num_control_inputs: 2
        init_vx: 0.0
        init_wz: 0.0
        init_acc: 0.0
        init_alpha: 0.0
        collision_foot_print_major_axis: 0.8
        collision_foot_print_minor_axis: 0.4
        pos_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 373
        vel_inf_noise:
          enable: false
          type: "normal"
          min_noise: -0.05
          max_noise: +0.05
          mean_noise: 1e-6
          std_dev: 0.01
          seed: 1473  
     
          
    corridor:
      num_lines: 2
      # upper wall
      line_1:
        start: [-14.0, -3.4]
        end: [14.0, -3.4]
        width: 0.02
        color: [0.0, 0.0, 0.0, 1.0]

      # lower wall
      line_2:
        start: [-14.0, +3.4]
        end: [14.0, +3.4]
        width: 0.02
        color: [0.0, 0.0, 0.0, 1.0]

    Lanes:
      num_lanes: 2
      # upper lane
      lane_1:
        start: [-14.0, -1.7]
        end: [14.0, -1.7]
        width: 3.4
        color: [0.0, 0.0, 0.0, 1.0]

      # lower lane
      lane_2:
        start: [-14.0, +1.7]
        end: [14.0, +1.7]
        width: 3.4
        color: [0.0, 0.0, 0.0, 1.0]


    agent_interface:
      model_step_dt: 0.001              # state integration step (s)
      integration_step_size: 0.001
      state_publisher_dt: 0.01  # odom/TF publish rate (s)
      fixed_frame: "odom"
    pid:
      kp_v: 3.0        # moderate — smooth response, ts ≈ 1.3s
      ki_v: 0.3        # eliminate steady state error slowly
      kd_v: 0.02       # small derivative, noise safe at 1000 Hz
      kp_w: 3.0        # same for angular
      ki_w: 0.2
      kd_w: 0.02
      acc_max: 1.0    # match your robot ax_max from yaml
      alpha_max: 0.7   # match your robot az_max
    
    visualization:
        vis_dt: 0.05 # update the plot with this rate

    lidar:
      vis_dt: 0.1          # scan publish rate (seconds)
      num_beams: 360        # number of rays per scan
      angle_min: -3.14159265358979   # start angle relative to agent heading (rad)
      angle_max:  3.14159265358979   # end angle relative to agent heading (rad)
      range_min: 0.05       # minimum valid range (m)
      range_max: 5.0       # maximum valid range / no-hit value (m)

    obstacles:
      type: "circle"
      num_obstacles: 6
      obstacle_1:
        position: [-4.0, 3.4, 0.0, -1.57]
        radius: 0.4
        color: [1.0, 0.0, 0.0, 1.0]

      obstacle_2:
        position: [-2.0, 3.0, 0.0, -1.57]
        radius: 0.4
        color: [1.0, 0.0, 0.0, 1.0]
      
      obstacle_3:
        position: [0.0,  3.0, 0.0, -1.57]
        radius: 0.4
        color: [1.0, 0.0, 0.0, 1.0]

      obstacle_4:
        position: [3.0,  3.0, 0.0, -1.57]
        radius: 0.4
        color: [1.0, 0.0, 0.0, 1.0]
      
      obstacle_5:
        position: [-7.0,  3.4, 0.0, -1.57]
        radius: 0.4
        color: [1.0, 0.0, 0.0, 1.0]

      obstacle_6:
        position: [-9.0,  3.4, 0.0, -1.57]
        radius: 0.4
        color: [1.0, 0.0, 0.0, 1.0]







