sector_tuner:
  ros__parameters:
    global_limit: 0.9
    n_sectors: 4

    Sector0:
      start: 0
      end: 80
      scaling: 0.8

    Sector1:
      start: 81
      end: 135
      scaling: 0.6

    Sector2:
      start: 135
      end: 215
      scaling: 0.9

    Sector3:
      start: 215
      end: 281
      scaling: 0.5